// Permission string constants — values must match exactly what the API returns.
// Never hardcode permission strings inline; always use these constants.
export const PERMISSIONS = {
  CONVERSATIONS: {
    READ:          "conversations.read",
    READ_ALL:      "conversations.read.all",
    ALL_READ:      "read_all_conversations",
    ALL_WRITE:     "write_all_conversations",
    MY_READ:       "read_my_conversations",
    MY_WRITE:      "write_my_conversations",
    ASSIGNED_READ: "read_assigned_conversations",
    WRITE:         "conversations.write",
    ASSIGN:        "conversations.assign",
    CLOSE:         "conversations.close",
    REOPEN:        "conversations.reopen",
  },
  USERS: {
    READ:      "users.read",
    READ_ALL:  "read_all_users",
    WRITE_ALL: "write_all_users",
    INVITE:    "users.invite",
    UPDATE:    "users.update",
    DELETE:    "users.delete",
    ROLE:      { CHANGE: "users.role.change" },
  },
  TEAMS:   { READ: "manage_teams" },
  REPORTS: { READ: "access_reports" },
  LABELS:  { READ: "manage_labels" },
  INBOXES: { READ: "manage_inboxes" },
  CHANNELS:           { READ: "manage_channels" },
  EMAIL_CHANNELS:     { READ: "manage_channels" },
  BROADCASTS:         { READ: "manage_broadcasts" },
  WHATSAPP_TEMPLATES: { READ: "manage_templates" },
  AGENTS:   { MANAGE: "manage_agents" },
  SETTINGS: { MANAGE: "manage_settings" },
  CANNED_RESPONSES: {
    ACCESS: "access_canned_responses",
    READ:   "canned_responses.read",
  },
  CONTACTS: {
    VIEW_INFO: "view_contact_info",
    READ:      "contacts.read",
  },
  MESSAGES: {
    SEND_ALL: "send_messages",
    READ:     "messages.read",
  },
  GROUPS: {
    READ:  "groups.read",
    WRITE: "groups.write",
  },
  PERMISSIONS: {
    READ:   "permissions.read",
    ASSIGN: { USER: "permissions.assign.user" },
  },
  ANALYTICS:       { READ: "analytics.read" },
  KNOWLEDGE_BASES: { READ: "knowledge_bases.read" },
  AUTOMATION:      { READ: "automation.read" },
  LICENSES:        { READ: "licenses.read" },
  ORGANIZATIONS:   { READ: "organizations.read" },
} as const;
